### ISSUE TITLE
lock and requirements ?!

### ISSUE THREAD

**Issue by goern** [thoth-station/cli-examples#11]
Why do we have `requirements.txt` and `Pipfile.lock` in this repo?

/assign @fridex @KPostOffice

**Comment by fridex** [comment]
> Why do we have `requirements.txt` and `Pipfile.lock` in this repo?

IIRC it was demonstrating support for requirements.txt and Pipfile.lock, but I'm not 100% sure with that. I think we can stick with Pipenv files:

https://github.com/thoth-station/cli-examples/blob/bfd4f0e42a7a56b347ed82636bdcc8892d07eed2/.thoth.yaml#L3
